TRAIN:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 32
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: /mnt/lustre/talhussan/TDAL/slowfast/checkpoints/checkpoint_epoch_00440.pyth
  CHECKPOINT_TYPE: pytorch

AUG:
  ENABLE: True
  NUM_SAMPLE: 2
  
DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3, 3]
  PATH_TO_DATA_DIR: /mnt/lustre/talhussan/TDAL/slowfast/data/Right
  PATH_LABEL_SEPARATOR: ','
  RANDOM_FLIP: False

SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
  
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]

NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product

BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200

SOLVER:
  BASE_LR: 0.001
  LR_POLICY: cosine
  MAX_EPOCH: 2000
  #MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 34.0
  WARMUP_START_LR: 0.001
  OPTIMIZING_METHOD: sgd

MODEL:
  NUM_CLASSES: 16
  ARCH: slowfast
  MODEL_NAME: SlowFast
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5

TEST:
  ENABLE: False
  CHECKPOINT_FILE_PATH: 
  CHECKPOINT_TYPE: pytorch
  DATASET: kinetics
  BATCH_SIZE: 64

DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True

TENSORBOARD:
  ENABLE: True
  CLASS_NAMES_PATH: /mnt/lustre/talhussan/TDAL/slowfast/data/class_names.json
  LOG_DIR: /mnt/lustre/talhussan/TDAL/slowfast/result/Right
  CONFUSION_MATRIX:
    ENABLE: True
    FIGSIZE: [8, 8]
  HISTOGRAM:
    ENABLE: True
  MODEL_VIS:
    ENABLE: True
    MODEL_WEIGHTS: False
    ACTIVATIONS: False
    INPUT_VIDEO: False
    LAYER_LIST: [head/pathway0_avgpool, head/pathway1_avgpool]
    GRAD_CAM:
      ENABLE: False
      LAYER_LIST: [head/pathway0_avgpool, head/pathway1_avgpool]

NUM_GPUS: 4
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: /mnt/lustre/talhussan/TDAL/slowfast/result/Right
